version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "9000:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
    networks:
      - jenkins-net
networks:
  jenkins-net:
