FROM jenkins/jenkins
USER root
RUN apt-get update  \
      && apt-get install -y sudo libltdl7 \
      && rm -rf /var/lib/apt/lists/*
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
